function singleMc = calculateSingleMatchingCost(im_l, im_r, x_l, y_l, x_r, y_r, windowSize)
    switch windowSize
        case 3
            singleMc = sum( [sum((im_r(x_r - 1, y_r - 1, :) - im_l(x_l - 1, y_l - 1, :)).^2), sum((im_r(x_r - 1, y_r, :) - im_l(x_l - 1, y_l, :)).^2), sum((im_r(x_r - 1, y_r + 1, :) - im_l(x_l - 1, y_l + 1, :)).^2), ...
                             sum((im_r(x_r    , y_r - 1, :) - im_l(x_l    , y_l - 1, :)).^2), sum((im_r(x_r    , y_r, :) - im_l(x_l    , y_l, :)).^2), sum((im_r(x_r    , y_r + 1, :) - im_l(x_l    , y_l + 1, :)).^2), ...
                             sum((im_r(x_r + 1, y_r - 1, :) - im_l(x_l + 1, y_l - 1, :)).^2), sum((im_r(x_r + 1, y_r, :) - im_l(x_l + 1, y_l, :)).^2), sum((im_r(x_r + 1, y_r + 1, :) - im_l(x_l + 1, y_l + 1, :)).^2)]);
        case 5
            singleMc = sum( [sum((im_r(x_r - 2, y_r - 2, :) - im_l(x_l - 2, y_l - 2, :)).^2), sum((im_r(x_r - 2, y_r - 1, :) - im_l(x_l - 2, y_l - 1, :)).^2), sum((im_r(x_r - 2, y_r, :) - im_l(x_l - 2, y_l, :)).^2), sum((im_r(x_r - 2, y_r + 1, :) - im_l(x_l - 2, y_l + 1, :)).^2), sum((im_r(x_r - 2, y_r + 2, :) - im_l(x_l - 2, y_l + 2, :)).^2), ... 
                             sum((im_r(x_r - 1, y_r - 2, :) - im_l(x_l - 1, y_l - 2, :)).^2), sum((im_r(x_r - 1, y_r - 1, :) - im_l(x_l - 1, y_l - 1, :)).^2), sum((im_r(x_r - 1, y_r, :) - im_l(x_l - 1, y_l, :)).^2), sum((im_r(x_r - 1, y_r + 1, :) - im_l(x_l - 1, y_l + 1, :)).^2), sum((im_r(x_r - 1, y_r + 2, :) - im_l(x_l - 1, y_l + 2, :)).^2), ...
                             sum((im_r(x_r    , y_r - 2, :) - im_l(x_l    , y_l - 2, :)).^2), sum((im_r(x_r    , y_r - 1, :) - im_l(x_l    , y_l - 1, :)).^2), sum((im_r(x_r    , y_r, :) - im_l(x_l    , y_l, :)).^2), sum((im_r(x_r    , y_r + 1, :) - im_l(x_l    , y_l + 1, :)).^2), sum((im_r(x_r    , y_r + 2, :) - im_l(x_l    , y_l + 2, :)).^2), ...
                             sum((im_r(x_r + 1, y_r - 2, :) - im_l(x_l + 1, y_l - 2, :)).^2), sum((im_r(x_r + 1, y_r - 1, :) - im_l(x_l + 1, y_l - 1, :)).^2), sum((im_r(x_r + 1, y_r, :) - im_l(x_l + 1, y_l, :)).^2), sum((im_r(x_r + 1, y_r + 1, :) - im_l(x_l + 1, y_l + 1, :)).^2), sum((im_r(x_r + 1, y_r + 2, :) - im_l(x_l + 1, y_l + 2, :)).^2), ...
                             sum((im_r(x_r + 2, y_r - 2, :) - im_l(x_l + 2, y_l - 2, :)).^2), sum((im_r(x_r + 2, y_r - 1, :) - im_l(x_l + 2, y_l - 1, :)).^2), sum((im_r(x_r + 2, y_r, :) - im_l(x_l + 2, y_l, :)).^2), sum((im_r(x_r + 2, y_r + 1, :) - im_l(x_l + 2, y_l + 1, :)).^2), sum((im_r(x_r + 2, y_r + 2, :) - im_l(x_l + 2, y_l + 2, :)).^2)]);
    end
end